"""
Django settings for emprendimientos project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from django.test.runner import DiscoverRunner

from django.contrib.messages import constants as messages
import os
from decouple import config
import dj_database_url

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "asdf567&908-ADDF34")
DEBUG = os.getenv("DEBUG", "False") == "True"
#DEBUG = True

CORS_ALLOWED_ORIGINS = [
    'https://'+os.getenv("DOMAIN"),
    'http://localhost:3000',
    'http://localhost:8080',
    'http://localhost:5000',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:8080',
    'http://127.0.0.1:5000',
]

# Allow credentials (needed for cookies/sessions)
CORS_ALLOW_CREDENTIALS = True


# Allow all HTTP methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow these headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Allow Render domain
ALLOWED_HOSTS = ['*']

# Security settings for production

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access CSRF token
    CSRF_COOKIE_SAMESITE = 'Lax'  # Allow activation links from emails
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF trusted origins for Render
CSRF_TRUSTED_ORIGINS = [
    'https://'+os.getenv("DOMAIN"),
    'https://*.onrender.com',
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'gastronomia/static'),
]



#GDAL_LIBRARY_PATH = '/opt/homebrew/opt/gdal/lib/libgdal.dylib'
GEOS_LIBRARY_PATH = '/opt/homebrew/opt/geos/lib/libgeos_c.dylib'


# Application definition

SITE_ID = 1

INSTALLED_APPS = [
    'django.contrib.auth',
    'corsheaders',
    "phonenumber_field",
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'anymail',
    'django.contrib.sites', ## agregado 4 sept 2025
    'djoser',
    'rest_framework',
    'rest_framework.authtoken',
    #'gastronomia',
    'gastronomia.apps.GastronomiaConfig',
    
    
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        
        #'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 75
    
}


# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND')
ANYMAIL = {
    "MAILGUN_API_KEY": config('MAILGUN_API_KEY'),
    "MAILGUN_SENDER_DOMAIN": config('MAILGUN_SENDER_DOMAIN'),
    
}
# Default email settings
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
SERVER_EMAIL = config('SERVER_EMAIL')

# Domain and site settings (required by Djoser)
DOMAIN = config('DOMAIN')  # Change to your actual domain in production
SITE_NAME = config('SITE_NAME')  
USE_HTTPS = config('USE_HTTPS')  # Set to True in production


DJOSER = {
    "USER_EMAIL_UNIQUE": True,
    "SEND_ACTIVATION_EMAIL": True,
    "USER_CREATE_PASSWORD_RETYPE": True,       # expects "re_password" in the payload
    "PASSWORD_RESET_CONFIRM_URL": "password/reset/confirm/{uid}/{token}",
    "ACTIVATION_URL": 'auth/users/activation/{uid}/{token}', 
    "SERIALIZERS": {
        "user_create": "gastronomia.serializers.CustomUserCreateSerializer",
        "user": "gastronomia.serializers.CustomUserSerializer",
    },

    
    "EMAIL": {
        "activation": "gastronomia.email.ActivationEmail",
        "password_reset": "gastronomia.email.PasswordResetEmail",
        
    },
    "DOMAIN": DOMAIN,
    "SITE_NAME": SITE_NAME,
    
}



#DJOSER = {
#    'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',
#    'USERNAME_RESET_CONFIRM_URL': 'username/reset/confirm/{uid}/{token}',
#    'ACTIVATION_URL': 'activate/{uid}/{token}',
#    'SEND_ACTIVATION_EMAIL': True,
#    'SEND_CONFIRMATION_EMAIL': True,
#    'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND': True,
#    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,
#    'EMAIL': {
#        'activation': 'emprendimientos.email.ActivationEmail',
#        'confirmation': 'emprendimientos.email.ConfirmationEmail',
#        'password_reset': 'emprendimientos.email.PasswordResetEmail',
#        'password_changed_confirmation': 'emprendimientos.email.PasswordChangedConfirmationEmail',
#    }
#}





MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
]

CORS_ALLOW_ALL_ORIGINS = True


# CORS_ALLOWED_ORIGIN_REGEXES = [
#     'http://127.0.0.1:8000',
# ]


#CORS_ALLOWED_ORIGINS = [
#    'http://127.0.0.1:8000',
#]
#from corsheaders.defaults import default_methods

#CORS_ALLOW_METHODS = list(default_methods)
#from corsheaders.defaults import default_headers

#CORS_ALLOW_HEADERS = list(default_headers)

#CORS_ALLOW_CREDENTIALS: True



ROOT_URLCONF = 'emprendimientos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),  # Make sure this is added
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'emprendimientos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'emps',
#        'USER': 'postgres',
#        'PASSWORD': 'marlon',
#        'HOST': 'localhost',
#        'PORT': '',
#    }   
#}

#db_from_env = dj_database_url.config(conn_max_age=600)
#DATABASES['default'].update(db_from_env)
DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True
    )
}



# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



# agreagdo recien

#DEBUG = True



#DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# AUTH_USER_MODEL = 'gastronomia.User'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

WHITENOISE_MANIFEST_STRICT = False

