# Generated by Django 5.2.6 on 2025-12-31 16:39

import django.contrib.postgres.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('parroquia', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('propietario', models.CharField(max_length=200)),
                ('tipo_turismo', models.CharField(default='No especificado', max_length=200)),
                ('experiencia', models.IntegerField(default=0)),
                ('asociacion', models.CharField(default='No', max_length=20)),
                ('ruc', models.CharField(default='No', max_length=100)),
                ('estado_local', models.CharField(choices=[('Propio', 'Propio'), ('Arrendado', 'Arrendado'), ('Otro', 'Otro')], default='Propio', max_length=20)),
                ('servicios_produccion', models.CharField(max_length=1000)),
                ('licencia_gad_loja', models.CharField(default='No', max_length=100)),
                ('arcsa', models.CharField(default='No', max_length=100)),
                ('turismo', models.CharField(default='No', max_length=100)),
                ('equipos', models.CharField(max_length=1000)),
                ('pagina_web', models.URLField(default='No', max_length=500)),
                ('facebook', models.CharField(default='No', max_length=500)),
                ('instagram', models.CharField(default='No', max_length=500)),
                ('tiktok', models.CharField(default='No', max_length=500)),
                ('whatsapp', models.CharField(default='No', max_length=500)),
                ('tipo', models.CharField(max_length=100)),
                ('mesas', models.IntegerField(default=0)),
                ('plazas', models.IntegerField(default=0)),
                ('banio', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2)),
                ('complementarios', models.CharField(max_length=1000)),
                ('oferta', models.CharField(max_length=600)),
                ('menu', models.TextField(max_length=1200, null=True)),
                ('tipo_servicio', models.CharField(max_length=400)),
                ('precio_promedio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('procesos', models.CharField(max_length=400)),
                ('materia_prima', models.CharField(max_length=400)),
                ('proveedores', models.CharField(max_length=400)),
                ('numero_proveedores', models.IntegerField()),
                ('numero_mujeres', models.IntegerField(default=0)),
                ('numero_hombres', models.IntegerField(default=0)),
                ('tiempo_trabajando', models.IntegerField(default=0)),
                ('personal_capacitado', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2)),
                ('frecuencia_capacitacion', models.CharField(max_length=200)),
                ('dependencia_ingresos', models.CharField(max_length=200)),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], default='otro', max_length=20)),
                ('nivel_educacion', models.CharField(default='No especificado', max_length=200)),
                ('edad', models.IntegerField(default=0)),
                ('estado_civil', models.CharField(max_length=200)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('horario', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True, default='https://picsum.photos/300/30')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('gallery_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gastronomia.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='gastronomia.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comment Replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='EC')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('pic', models.URLField(blank=True, default='https://picsum.photos/300/30')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='gastronomia.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='gastronomia.establecimiento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'establecimiento')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='gastronomia.establecimiento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'establecimiento')},
            },
        ),
    ]
