# Generated by Django 5.2.6 on 2025-09-03 19:22

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('ruc', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('parroquia', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('propietario', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('redes_sociales', models.CharField(max_length=100)),
                ('asociacion', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('equipos', models.CharField(max_length=1000)),
                ('equipos_cocina', models.CharField(max_length=1000)),
                ('servicios_complementarios', models.CharField(max_length=1000)),
                ('numero_mesas', models.IntegerField()),
                ('plazas', models.IntegerField()),
                ('banio', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20)),
                ('oferta', models.CharField(max_length=400)),
                ('tipo_servicio', models.CharField(max_length=400)),
                ('menu', models.TextField(max_length=1200, null=True)),
                ('precio_promedio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proceso', models.CharField(max_length=400)),
                ('materias_primas', models.CharField(max_length=400)),
                ('tipo_materia_prima', models.CharField(max_length=400)),
                ('numero_mujeres', models.IntegerField()),
                ('numero_hombres', models.IntegerField()),
                ('formacion_academica', models.CharField(max_length=200)),
                ('personal_capacitado', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('frecuencia_capacitacion', models.CharField(max_length=200)),
                ('empleados_formacion', models.CharField(max_length=200)),
                ('licencia_anual', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gastronomia.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='EC')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('pic', models.URLField(blank=True, default='https://picsum.photos/300/30')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='gastronomia.establecimiento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'establecimiento')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='gastronomia.establecimiento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'establecimiento')},
            },
        ),
    ]
