# Generated by Django 5.2.6 on 2025-09-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establecimiento',
            old_name='redes_sociales',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='establecimiento',
            old_name='equipos_cocina',
            new_name='complementarios',
        ),
        migrations.RenameField(
            model_name='establecimiento',
            old_name='empleados_formacion',
            new_name='dependencia_ingresos',
        ),
        migrations.RenameField(
            model_name='establecimiento',
            old_name='formacion_academica',
            new_name='estado_civil',
        ),
        migrations.RenameField(
            model_name='establecimiento',
            old_name='local',
            new_name='horario',
        ),
        migrations.RenameField(
            model_name='establecimiento',
            old_name='materias_primas',
            new_name='materia_prima',
        ),
        migrations.RenameField(
            model_name='establecimiento',
            old_name='numero_mesas',
            new_name='numero_proveedores',
        ),
        migrations.RenameField(
            model_name='establecimiento',
            old_name='proceso',
            new_name='procesos',
        ),
        migrations.RenameField(
            model_name='establecimiento',
            old_name='tipo_materia_prima',
            new_name='proveedores',
        ),
        migrations.RenameField(
            model_name='establecimiento',
            old_name='servicios_complementarios',
            new_name='servicios_produccion',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='licencia_anual',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='url',
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='arcsa',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='estado_local',
            field=models.CharField(choices=[('Propio', 'Propio'), ('Arrendado', 'Arrendado'), ('Otro', 'Otro')], default='Propio', max_length=20),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='experiencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='facebook',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='genero',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='instagram',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='licencia_gad_loja',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='mesas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='nivel_educacion',
            field=models.CharField(default='No especificado', max_length=200),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='pagina_web',
            field=models.URLField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='tiempo_trabajando',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='tiktok',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='tipo_turismo',
            field=models.CharField(default='No especificado', max_length=200),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='turismo',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='whatsapp',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='asociacion',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='banio',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='numero_hombres',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='numero_mujeres',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='personal_capacitado',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='plazas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='ruc',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2),
        ),
    ]
