# Generated by Django 5.2.6 on 2025-09-24 21:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomia', '0002_rename_redes_sociales_establecimiento_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='gallery_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='photo_url',
            field=models.URLField(blank=True, default='https://picsum.photos/300/30'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
