# Generated by Django 5.2.6 on 2025-09-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomia', '0003_establecimiento_gallery_urls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='banio',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='facebook',
            field=models.CharField(default='No', max_length=500),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='instagram',
            field=models.CharField(default='No', max_length=500),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='pagina_web',
            field=models.URLField(default='No', max_length=500),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='tiktok',
            field=models.CharField(default='No', max_length=500),
        ),
    ]
