# Generated by Django 5.2.6 on 2025-09-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomia', '0004_alter_establecimiento_banio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='whatsapp',
            field=models.CharField(default='No', max_length=500),
        ),
    ]
