# Generated by Django 5.2.6 on 2025-09-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastronomia', '0005_alter_establecimiento_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='arcsa',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='asociacion',
            field=models.CharField(default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='licencia_gad_loja',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='oferta',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='ruc',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='turismo',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
